# # 이름 짓기
# name: Github Actions 연습하기
# # 언제 이 작업을 실행할지 정의
# # push: github에 push할 때마다 실행
# on: push

# jobs:
#   push-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: 첫 번째 작업
#         run: echo "첫 번째 작업 실행 중"

#       - name: 여러 명령어 문장 작성하기
#         run: |
#           echo "첫 번째 명령어"
#           echo "두 번째 명령어"

#       - name: Github Actions 자체에 저장되어 있는 변수 사용해보기
#         run: |
#           echo $GITHUB_SHA
#           echo $GITHUB_REPOSITORY

#       - name: Github Actions Secret 변수 사용해보기
#         run: |
#           echo ${{ secrets.MY_NAME }}
#           echo ${{ secrets.MY_HOBBY }}

# ---------------------------------------------------------------------

# name: Github Actions로 테스트 자동화하기
# on: push

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Github Repository 불러오기
#         uses: actions/checkout@v6

#       - name: Node.js 설치하기
#         uses: actions/setup-node@v6
#         with:
#           node-version: "24"
#           cache: "npm"

#       - name: 의존성(라이브러리) 설치
#         run: npm ci

#       - name: 테스트 실행하기
#         run: npm run test

# ---------------------------------------------------------------------

# name: Github Actions로 작업 병렬로 실행하기
# on: push

# jobs:
#   first_job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: 첫 번째 작업의 1단계
#         run: echo "첫 번째 작업의 첫 번째 단계입니다."
#       - name: 첫 번째 작업의 2단계
#         run: echo "첫 번째 작업의 두 번째 단계입니다."

#   second_job:
#     runs-on: ubuntu-latest
#     needs: first_job
#     steps:
#       - name: 두 번째 작업의 1단계
#         run: echo "두 번째 작업의 첫 번째 단계입니다."
#       - name: 두 번째 작업의 2단계
#         run: echo "두 번째 작업의 두 번째 단계입니다."

# ---------------------------------------------------------------------

# name: output 연습
# on: push

# jobs:
#   create-output:
#     runs-on: ubuntu-latest
#     # 현재 job의 step 중에 save-output이라는 id를 가진 step의
#     # output의 키가 message인 값을 abc라는 이름으로 내보내기 할거야.
#     outputs:
#       abc: ${{ steps.save-output.outputs.message }}
#     steps:
#       - name: output 저장
#         id: save-output
#         run: echo "message=안녕" >> $GITHUB_OUTPUT

#       - name: output 사용
#         run: echo "저장된 키는 ${{ steps.save-output.outputs.message }}입니다."

#   use-output:
#     runs-on: ubuntu-latest
#     # 위의 job(create-output)에서 만든 outputs를 해당 job(use-output)에서 사용하기 위해선
#     # 위 job(create-output)이 실패하면 안되기 때문에 needs가 필요합니다.
#     needs: create-output
#     steps:
#       - name: output 사용
#         run: echo "이 job에서 사용할 output은 ${{ needs.create-output.outputs.abc }}입니다."

# ---------------------------------------------------------------------

name: if 조건 연습
on:
  push:
    branches:
      - develop
      - main

jobs:
  if-test:
    runs-on: ubuntu-latest
    steps:
      - name: develop 브랜치일 때만 실행
        if: github.ref == 'refs/heads/develop'
        run: echo "develop 브랜치에 푸시되었고, Staging 환경에 배포합니다."

      - name: main 브랜치일 때만 실행
        if: github.ref == 'refs/heads/main'
        run: echo "main 브랜치에 푸시되었고, Production 환경에 배포합니다."
